version: '3.8'

services:
  mcp:
    image: ghcr.io/github/github-mcp-server:latest
    ports:
      - "8081:8080"
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    tty: true
    stdin_open: true
    restart: unless-stopped 